name: jnm_ui
description: Pacote de UI Padrão JNMoura.
version: 1.0.0
homepage: https://jnmoura.com.br

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  elevarm_icons: ^1.3.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_svg: ^2.0.17
  flutter_typeahead: ^5.2.0
  intl: ^0.20.2
  just_the_tooltip: ^0.0.12
  photo_view: ^0.15.0
  pinput: ^5.0.1
  syncfusion_flutter_charts: ^29.1.35
  syncfusion_flutter_datepicker: ^29.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter